robot1_amcl:
  ros__parameters:
    use_sim_time: False
    min_particles: 300
    max_particles: 1500
    max_beams: 40
    update_min_d: 0.15
    update_min_a: 0.12
    laser_model_type: "likelihood_field"
    laser_likelihood_max_dist: 2.0
    z_hit: 0.6
    z_rand: 0.4
    laser_max_range: 100.0
    beam_skip_distance: 0.5
    do_beamskip: true
    resample_interval: 1
    save_pose_rate: 0.5
    tf_broadcast: true
    transform_tolerance: 1.0
    scan_topic: robot1/scan
