#!/usr/bin/env python3
import os
from pathlib import Path
import re
import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'DETAILED_INVENTORY.md'

launch_dir = ROOT / 'launch'
params_dir = ROOT / 'params'

# simple patterns are handled inline; no global regex required


def scan_launch_file(p: Path):
    content = p.read_text(encoding='utf-8', errors='ignore')
    nodes = []
    includes = []
    # crude parsing for Node(package='pkg', executable='exe') patterns
    for m in re.finditer(r"Node\(.*?package\s*=\s*['\"](?P<pkg>[^'\"]+)['\"].*?executable\s*=\s*['\"](?P<exe>[^'\"]+)['\"]", content, re.S):
        nodes.append(f"{m.group('pkg')}/{m.group('exe')}")
    # find IncludeLaunchDescription calls
    for m in re.finditer(r"IncludeLaunchDescription\(.*?PythonLaunchDescriptionSource\(.*?['\"](?P<path>[^'\"]+)['\"]", content, re.S):
        includes.append(m.group('path'))
    # find ros2 launch ExecuteProcess invocations
    for m in re.finditer(r"ExecuteProcess\(.*?cmd\s*=\s*\[([^\]]+)\]", content, re.S):
        cmd = m.group(1)
        if 'ros2' in cmd and 'launch' in cmd:
            includes.append('ros2 launch ...')
    return nodes, includes


def scan_params_file(p: Path):
    try:
        data = yaml.safe_load(p.read_text())
        if isinstance(data, dict):
            keys = list(data.keys())
            return keys
    except Exception:
        return []
    return []

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('# Detailed Inventory\n\n')
    f.write('Generated by scripts/generate_detailed_inventory.py\n\n')

    f.write('## Launch files\n')
    if launch_dir.exists():
        for p in sorted(launch_dir.glob('**/*.py')):
            f.write(f'- {p.relative_to(ROOT)}\n')
            nodes, includes = scan_launch_file(p)
            if nodes:
                f.write('  - Nodes:\n')
                for n in nodes:
                    f.write(f'    - {n}\n')
            if includes:
                f.write('  - Includes:\n')
                for inc in includes:
                    f.write(f'    - {inc}\n')
    else:
        f.write('- (none)\n')
    f.write('\n')

    f.write('## Params files\n')
    if params_dir.exists():
        for p in sorted(params_dir.glob('**/*.*')):
            f.write(f'- {p.relative_to(ROOT)}\n')
            keys = scan_params_file(p)
            if keys:
                f.write('  - Top keys:\n')
                for k in keys:
                    f.write(f'    - {k}\n')
    else:
        f.write('- (none)\n')
    f.write('\n')

print('Wrote', OUT)
