#!/usr/bin/env python3
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]  # yahboomcar_ros2_ws
OUT = ROOT / 'INVENTORY.md'

sections = []

def list_dir(p: Path, pattern=None):
    if not p.exists():
        return []
    files = []
    for fp in sorted(p.rglob(pattern) if pattern else p.rglob('*')):
        if fp.is_file():
            files.append(fp.relative_to(ROOT))
    return files

# gather
launch_files = list_dir(ROOT / 'launch')
params_files = list_dir(ROOT / 'params')
src_files = list_dir(ROOT / 'src')
scripts_files = list_dir(ROOT / 'scripts')

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('# Inventory for yahboomcar_ros2_ws\n\n')
    f.write('Generated by scripts/generate_inventory.py\n\n')

    f.write('## Launch files\n')
    if launch_files:
        for p in launch_files:
            f.write(f'- {p}\n')
    else:
        f.write('- (none)\n')
    f.write('\n')

    f.write('## Params files\n')
    if params_files:
        for p in params_files:
            f.write(f'- {p}\n')
    else:
        f.write('- (none)\n')
    f.write('\n')

    f.write('## Source files\n')
    if src_files:
        for p in src_files:
            f.write(f'- {p}\n')
    else:
        f.write('- (none)\n')
    f.write('\n')

    f.write('## Scripts\n')
    if scripts_files:
        for p in scripts_files:
            f.write(f'- {p}\n')
    else:
        f.write('- (none)\n')
    f.write('\n')

print('Wrote', OUT)
